version: '3.8'

services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ride-network


  # Auth Service
  auth:
    build: ./services/auth
    container_name: auth
    ports:
      - "5001:5001"
    environment:
      - SECRET=mysecretkey
    depends_on:
      - redis
    networks:
      - ride-network


  # Rider Service
  rider:
    build: ./services/rider
    container_name: rider
    ports:
      - "5002:5002"
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - auth
    networks:
      - ride-network


  # Driver Service
  driver:
    build: ./services/driver
    container_name: driver
    ports:
      - "5003:5003"
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - auth
    networks:
      - ride-network


  # Matching Service
  matching:
    build: ./services/matching
    container_name: matching
    ports:
      - "5004:5004"
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - rider
      - driver
    networks:
      - ride-network


  # Trip Service
  trip:
    build: ./services/trip
    container_name: trip
    ports:
      - "5005:5005"
    depends_on:
      - matching
    networks:
      - ride-network


  # Payment Service
  payment:
    build: ./services/payment
    container_name: payment
    ports:
      - "5006:5006"
    depends_on:
      - trip
    networks:
      - ride-network


  # Geo Location Service
  geo:
    build: ./services/geo-location
    container_name: geo
    ports:
      - "5007:5007"
    networks:
      - ride-network


  # API Gateway
  gateway:
    build: ./api-gateway
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_URL=http://auth:5001
      - RIDER_URL=http://rider:5002
      - DRIVER_URL=http://driver:5003
      - MATCHING_URL=http://matching:5004
      - TRIP_URL=http://trip:5005
      - PAYMENT_URL=http://payment:5006
      - GEO_URL=http://geo:5007
    depends_on:
      - auth
      - rider
      - driver
      - matching
      - trip
      - payment
      - geo
    networks:
      - ride-network


networks:
  ride-network:
    driver: bridge
